spring.application.name=thymeleafdemo

server.port=8091

countries= brazil, France, India, japan 

langues= javaScrip, C programing , Css, Sql 

system= msi , mac , lg , lenovo , asus , aser

logging.level.org.springframework.security=DEBUG